class District {
  final String name;
  final List<String> sectors;

  const District({required this.name, required this.sectors});
}

class LocationData {
  static final Map<String, List<District>> provinceData = {
    'Kigali City': [
      const District(
        name: 'Gasabo',
        sectors: [
          'Bumbogo',
          'Gatsata',
          'Gikomero',
          'Gisozi',
          'Jabana',
          'Jali',
          'Kacyiru',
          'Kimihurura',
          'Kimironko',
          'Kinyinya',
          'Ndera',
          'Nduba',
          'Remera',
          'Rusororo',
          'Rutunga',
        ],
      ),
      const District(
        name: 'Kicukiro',
        sectors: [
          'Gahanga',
          'Gatenga',
          'Gikondo',
          'Kagarama',
          'Kanombe',
          'Kicukiro',
          'Kigarama',
          'Masaka',
          'Niboye',
          'Nyarugunga',
        ],
      ),
      const District(
        name: 'Nyarugenge',
        sectors: [
          'Gitega',
          'Kanyinya',
          'Kigali',
          'Kimisagara',
          'Mageregere',
          'Muhima',
          'Nyakabanda',
          'Nyamirambo',
          'Nyarugenge',
          'Rwezamenyo',
        ],
      ),
    ],
    'Eastern Province': [
      const District(
        name: 'Bugesera',
        sectors: [
          'Gashora',
          'Juru',
          'Kamabuye',
          'Mareba',
          'Mayange',
          'Musenyi',
          'Mwogo',
          'Ngeruka',
          'Ntarama',
          'Nyamata',
          'Nyarugenge',
          'Rilima',
          'Ruhuha',
          'Rweru',
          'Shyara',
        ],
      ),
      const District(
        name: 'Gatsibo',
        sectors: [
          'Gasange',
          'Gatsibo',
          'Gitoki',
          'Kabarore',
          'Kageyo',
          'Kiramuruzi',
          'Kiziguro',
          'Muhura',
          'Murambi',
          'Ngarama',
          'Nyagihanga',
          'Remera',
          'Rugarama',
          'Rwimbogo',
        ],
      ),
      const District(
        name: 'Kayonza',
        sectors: [
          'Gahini',
          'Kabare',
          'Kabarondo',
          'Mukarange',
          'Murama',
          'Murundi',
          'Mwiri',
          'Ndego',
          'Nyamirama',
          'Rukara',
          'Ruramira',
          'Rwinkwavu',
        ],
      ),
      const District(
        name: 'Kirehe',
        sectors: [
          'Gahara',
          'Gatore',
          'Kigarama',
          'Kigina',
          'Kirehe',
          'Mahama',
          'Mpanga',
          'Musaza',
          'Mushikiri',
          'Nasho',
          'Nyamugari',
          'Nyarubuye',
        ],
      ),
      const District(
        name: 'Ngoma',
        sectors: [
          'Gashanda',
          'Jarama',
          'Karembo',
          'Kazo',
          'Kibungo',
          'Mugesera',
          'Murama',
          'Mutenderi',
          'Remera',
          'Rukira',
          'Rukumberi',
          'Rurenge',
          'Sake',
          'Zaza',
        ],
      ),
      const District(
        name: 'Nyagatare',
        sectors: [
          'Gatunda',
          'Karama',
          'Karangazi',
          'Katabagemu',
          'Kiyombe',
          'Matimba',
          'Mimuli',
          'Mukama',
          'Musheli',
          'Nyagatare',
          'Rukomo',
          'Rwempasha',
          'Rwimiyaga',
          'Tabagwe',
        ],
      ),
      const District(
        name: 'Rwamagana',
        sectors: [
          'Fumbwe',
          'Gahengeri',
          'Gishari',
          'Karenge',
          'Kigabiro',
          'Muhazi',
          'Munyaga',
          'Munyiginya',
          'Musha',
          'Muyumbu',
          'Mwulire',
          'Nyakariro',
          'Nzige',
          'Rubona',
        ],
      ),
    ],
    'Northern Province': [
      const District(
        name: 'Burera',
        sectors: [
          'Bungwe',
          'Butaro',
          'Cyanika',
          'Cyeru',
          'Gahunga',
          'Gatebe',
          'Gitovu',
          'Kagogo',
          'Kinoni',
          'Kinyababa',
          'Kivuye',
          'Nemba',
          'Rugarama',
          'Rugendabari',
          'Ruhunde',
          'Rusarabuye',
          'Rwerere',
        ],
      ),
      const District(
        name: 'Gakenke',
        sectors: [
          'Busengo',
          'Coko',
          'Cyabingo',
          'Gakenke',
          'Gashenyi',
          'Janja',
          'Kamubuga',
          'Karambo',
          'Kivuruga',
          'Mataba',
          'Minazi',
          'Mugunga',
          'Muhondo',
          'Muyongwe',
          'Muzo',
          'Nemba',
          'Ruli',
          'Rusasa',
          'Rushashi',
        ],
      ),
      const District(
        name: 'Gicumbi',
        sectors: [
          'Bukure',
          'Bwisige',
          'Byumba',
          'Cyumba',
          'Giti',
          'Kaniga',
          'Manyagiro',
          'Miyove',
          'Mukarange',
          'Muko',
          'Mutete',
          'Nyamiyaga',
          'Nyankenke',
          'Rubaya',
          'Rukomo',
          'Rushaki',
          'Rutare',
          'Ruvune',
          'Rwamiko',
          'Shangasha',
        ],
      ),
      const District(
        name: 'Musanze',
        sectors: [
          'Busogo',
          'Cyuve',
          'Gacaca',
          'Gashaki',
          'Gataraga',
          'Kimonyi',
          'Kinigi',
          'Muhoza',
          'Muko',
          'Musanze',
          'Nkotsi',
          'Nyange',
          'Remera',
          'Rwaza',
          'Shingiro',
        ],
      ),
      const District(
        name: 'Rulindo',
        sectors: [
          'Base',
          'Burega',
          'Bushoki',
          'Buyoga',
          'Cyinzuzi',
          'Cyungo',
          'Kinihira',
          'Kisaro',
          'Masoro',
          'Mbogo',
          'Murambi',
          'Ngoma',
          'Ntarabana',
          'Rukozo',
          'Rusiga',
          'Shyorongi',
          'Tumba',
        ],
      ),
    ],
    'Southern Province': [
      const District(
        name: 'Gisagara',
        sectors: [
          'Gikonko',
          'Gishubi',
          'Kansi',
          'Kibilizi',
          'Kigembe',
          'Mamba',
          'Muganza',
          'Mugombwa',
          'Mukindo',
          'Musha',
          'Ndora',
          'Nyanza',
          'Save',
        ],
      ),
      const District(
        name: 'Huye',
        sectors: [
          'Gishamvu',
          'Huye',
          'Karama',
          'Kigoma',
          'Kinazi',
          'Maraba',
          'Mbazi',
          'Mukura',
          'Ngoma',
          'Ruhashya',
          'Rusatira',
          'Rwaniro',
          'Simbi',
          'Tumba',
        ],
      ),
      const District(
        name: 'Kamonyi',
        sectors: [
          'Gacurabwenge',
          'Karama',
          'Kayenzi',
          'Kayumbu',
          'Mugina',
          'Musambira',
          'Ngamba',
          'Nyamiyaga',
          'Nyarubaka',
          'Rugarika',
          'Rukoma',
          'Runda',
        ],
      ),
      const District(
        name: 'Muhanga',
        sectors: [
          'Cyeza',
          'Kabacuzi',
          'Kibangu',
          'Kiyumba',
          'Muhanga',
          'Mushishiro',
          'Nyabinoni',
          'Nyamabuye',
          'Nyarusange',
          'Rongi',
          'Rugendabari',
          'Shyogwe',
        ],
      ),
      const District(
        name: 'Nyamagabe',
        sectors: [
          'Buruhukiro',
          'Cyanika',
          'Gasaka',
          'Gatare',
          'Kaduha',
          'Kamegeri',
          'Kibirizi',
          'Kibumbwe',
          'Kitabi',
          'Mbazi',
          'Mugano',
          'Musange',
          'Musebeya',
          'Mushubi',
          'Nkomane',
          'Tare',
          'Uwinkingi',
        ],
      ),
      const District(
        name: 'Nyanza',
        sectors: [
          'Busasamana',
          'Cyabakamyi',
          'Kibilizi',
          'Kigoma',
          'Mukingo',
          'Muyira',
          'Ntyazo',
          'Nyagisozi',
          'Rwabicuma',
        ],
      ),
      const District(
        name: 'Nyaruguru',
        sectors: [
          'Busanze',
          'Cyahinda',
          'Kibeho',
          'Kivu',
          'Mata',
          'Muganza',
          'Munini',
          'Ngera',
          'Ngoma',
          'Nyabimata',
          'Nyagisozi',
          'Ruheru',
          'Ruramba',
          'Rusenge',
        ],
      ),
      const District(
        name: 'Ruhango',
        sectors: [
          'Bweramana',
          'Byimana',
          'Kabagari',
          'Kinazi',
          'Kinihira',
          'Mbuye',
          'Mwendo',
          'Ntongwe',
          'Ruhango',
        ],
      ),
    ],
    'Western Province': [
      const District(
        name: 'Karongi',
        sectors: [
          'Bwishyura',
          'Gashari',
          'Gishyita',
          'Gitesi',
          'Mubuga',
          'Murambi',
          'Murundi',
          'Mutuntu',
          'Rubengera',
          'Rugabano',
          'Ruganda',
          'Rwankuba',
          'Twumba',
        ],
      ),
      const District(
        name: 'Ngororero',
        sectors: [
          'Bwira',
          'Gatumba',
          'Hindiro',
          'Kabaya',
          'Kageyo',
          'Kavumu',
          'Matyazo',
          'Muhanda',
          'Muhororo',
          'Ndaro',
          'Ngororero',
          'Nyange',
          'Sovu',
        ],
      ),
      const District(
        name: 'Nyabihu',
        sectors: [
          'Bigogwe',
          'Jenda',
          'Jomba',
          'Kabatwa',
          'Karago',
          'Kintobo',
          'Mukamira',
          'Muringa',
          'Rambura',
          'Rugera',
          'Rurembo',
          'Shyira',
        ],
      ),
      const District(
        name: 'Nyamasheke',
        sectors: [
          'Bushekeri',
          'Bushenge',
          'Cyato',
          'Gihombo',
          'Kagano',
          'Kanjongo',
          'Karambi',
          'Karengera',
          'Kirimbi',
          'Macuba',
          'Mahembe',
          'Nyabitekeri',
          'Rangiro',
          'Ruharambya',
          'Shangi',
        ],
      ),
      const District(
        name: 'Rubavu',
        sectors: [
          'Bugeshi',
          'Busasamana',
          'Cyanzarwe',
          'Gisenyi',
          'Kanama',
          'Kanzenze',
          'Mudende',
          'Nyamyumba',
          'Nyundo',
          'Rubavu',
          'Rugerero',
        ],
      ),
      const District(
        name: 'Rusizi',
        sectors: [
          'Bugarama',
          'Butare',
          'Bweyeye',
          'Gashonga',
          'Giheke',
          'Gihundwe',
          'Gikundamvura',
          'Gitambi',
          'Kamembe',
          'Muganza',
          'Mururu',
          'Nkungu',
          'Nyakarenzo',
          'Nzahaha',
          'Rwimbogo',
        ],
      ),
      const District(
        name: 'Rutsiro',
        sectors: [
          'Boneza',
          'Gihango',
          'Kigeyo',
          'Kivumu',
          'Manihira',
          'Mukura',
          'Murunda',
          'Musasa',
          'Mushonyi',
          'Mushubati',
          'Nyabirasi',
          'Ruhango',
          'Rusebeya',
        ],
      ),
    ],
  };

  static List<String> getProvinces() => provinceData.keys.toList();

  static List<String> getDistrictsByProvince(String province) =>
      provinceData[province]?.map((d) => d.name).toList() ?? [];

  static List<String> getSectorsByDistrict(String province, String district) {
    final found = provinceData[province]?.firstWhere(
      (d) => d.name == district,
      orElse: () => const District(name: '', sectors: []),
    );
    return found?.sectors ?? [];
  }
}
