// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzohN-fo2XTmLmOl34KNXmlBOKevKY40Y',
    appId: '1:706024906983:android:04043de8f18de7a6f08242',
    messagingSenderId: '706024906983',
    projectId: 'potato-disease-811da',
    storageBucket: 'potato-disease-811da.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-c2AXvD1jRgTl38cBO_m8PvNHlz_Nckw',
    appId: '1:706024906983:web:38ab192f1e05dd4bf08242',
    messagingSenderId: '706024906983',
    projectId: 'potato-disease-811da',
    authDomain: 'potato-disease-811da.firebaseapp.com',
    storageBucket: 'potato-disease-811da.firebasestorage.app',
    measurementId: 'G-8E58LHZX89',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg8GNFPRVIm3ewubKqb1nMuUl_19DNdGg',
    appId: '1:706024906983:ios:5b7a044ae1d91949f08242',
    messagingSenderId: '706024906983',
    projectId: 'potato-disease-811da',
    storageBucket: 'potato-disease-811da.firebasestorage.app',
    iosBundleId: 'com.example.irishPotatoApp',
  );

}